create stream ref_equipment_ref_equip_type_stream with(PARTITIONS = 16) as 
select
refeq_gkey,
refeq_eq_subclass,
refeq_id,
refeq_scope,
refeq_data_source,
refeq_id_prefix,
refeq_id_nbr_only,
refeq_id_check_digit,
refeq_id_full,
refeq_class,
refeq_eqtyp_gkey,
refeq_length_mm,
refeq_height_mm,
refeq_width_mm,
refeq_iso_group,
refeq_tare_kg,
refeq_safe_kg,
refeq_owner,
refeq_operator,
refeq_prior_operator,
refeq_lease_expiration,
refeq_build_date,
refeq_no_stow_on_if_empty,
refeq_no_stow_on_if_laden,
refeq_must_stow_below_deck,
refeq_must_stow_above_deck,
refeq_p_o_s,
refeq_insulated,
refeq_material,
refeq_trnsp_type,
refeq_trnsp_id,
refeq_trnsp_time,
refeq_uses_accessories,
refeq_is_temperature_controlled,
refeq_oog_ok,
refeq_unsealable,
refeq_has_wheels,
refeq_is_open,
refeq_strength_code,
refeq_csc_expiration,
refeq_created,
refeq_creator,
refeq_changed,
refeq_changer,
refeq_life_cycle_state,
refeq_x_cord,
refeq_y_cord,
refeq_z_cord,
refeq_rfr_type,
refeq_is_starvent,
refeq_is_super_freeze_reefer,
refeq_is_controlled_atmo_reefer,
refeq_is_vented,
refeq_license_nbr,
refeq_license_state,
refeq_fed_inspect_exp,
refeq_state_inspect_exp,
refeq_axle_count,
refeq_is_triaxle,
refeq_fits_20,
refeq_fits_24,
refeq_fits_30,
refeq_fits_40,
refeq_fits_45,
refeq_fits_48,
refeq_fits_53,
refeq_door_kind,
refeq_tows_dolly,
refeq_semi_reefer_kind,
refeq_acry_description,
refeq_tank_rails,
refeq_scope_fk,
case when refeq_eqtyp_gkey_fk is null then '0' else refeq_eqtyp_gkey_fk end as refeq_eqtyp_gkey_fk,
refeq_owner_fk,
refeq_operator_fk,
refeq_prior_operator_fk,
refeq_operation,
refeq_timestamp,
refeq_multi_tenant_pk,
refeqty_gkey,
refeqty_id,
refeqty_reference_set,
refeqty_data_source,
refeqty_is_deprecated,
refeqty_is_archetype,
refeqty_archetype,
refeqty_clone_source,
refeqty_basic_length,
refeqty_nominal_length,
refeqty_nominal_height,
refeqty_rfr_type,
refeqty_class,
refeqty_iso_group,
refeqty_length_mm,
refeqty_height_mm,
refeqty_width_mm,
refeqty_tare_weight_kg,
refeqty_safe_weight_kg,
refeqty_description,
refeqty_pict_id,
refeqty_milliteus,
refeqty_uses_accessories,
refeqty_is_temperature_controlled,
refeqty_oog_ok,
refeqty_unsealable,
refeqty_has_wheels,
refeqty_is_open,
refeqty_fits_20,
refeqty_fits_24,
refeqty_fits_30,
refeqty_fits_40,
refeqty_fits_45,
refeqty_fits_48,
refeqty_fits_53,
refeqty_is_nopick,
refeqty_is_triaxle,
refeqty_is_super_freeze_reefer,
refeqty_is_controlled_atmo_reefer,
refeqty_no_stow_on_if_empty,
refeqty_no_stow_on_if_laden,
refeqty_must_stow_below_deck,
refeqty_must_stow_above_deck,
refeqty_created,
refeqty_creator,
refeqty_changed,
refeqty_changer,
refeqty_life_cycle_state,
refeqty_is_bombcart,
refeqty_is_cassette,
refeqty_teu_capacity,
refeqty_slot_labels,
refeqty_is_2x20NotAllowed,
refeqty_events_type_to_record,
refeqty_reference_set_fk,
refeqty_archetype_fk,
refeqty_clone_source_fk,
refeqty_operation,
refeqty_timestamp,
refeqty_multi_tenant_pk from ref_equipment_stream left join ref_equip_type on refeq_eqtyp_gkey_fk = refeqty_multi_tenant_pk partition by refeq_multi_tenant_pk;


create table ref_equipment_ref_equip_type (
refeq_gkey varchar,
refeq_eq_subclass varchar,
refeq_id varchar,
refeq_scope varchar,
refeq_data_source varchar,
refeq_id_prefix varchar,
refeq_id_nbr_only varchar,
refeq_id_check_digit varchar,
refeq_id_full varchar,
refeq_class varchar,
refeq_eqtyp_gkey varchar,
refeq_length_mm varchar,
refeq_height_mm varchar,
refeq_width_mm varchar,
refeq_iso_group varchar,
refeq_tare_kg varchar,
refeq_safe_kg varchar,
refeq_owner varchar,
refeq_operator varchar,
refeq_prior_operator varchar,
refeq_lease_expiration varchar,
refeq_build_date varchar,
refeq_no_stow_on_if_empty varchar,
refeq_no_stow_on_if_laden varchar,
refeq_must_stow_below_deck varchar,
refeq_must_stow_above_deck varchar,
refeq_p_o_s varchar,
refeq_insulated varchar,
refeq_material varchar,
refeq_trnsp_type varchar,
refeq_trnsp_id varchar,
refeq_trnsp_time varchar,
refeq_uses_accessories varchar,
refeq_is_temperature_controlled varchar,
refeq_oog_ok varchar,
refeq_unsealable varchar,
refeq_has_wheels varchar,
refeq_is_open varchar,
refeq_strength_code varchar,
refeq_csc_expiration varchar,
refeq_created varchar,
refeq_creator varchar,
refeq_changed varchar,
refeq_changer varchar,
refeq_life_cycle_state varchar,
refeq_x_cord varchar,
refeq_y_cord varchar,
refeq_z_cord varchar,
refeq_rfr_type varchar,
refeq_is_starvent varchar,
refeq_is_super_freeze_reefer varchar,
refeq_is_controlled_atmo_reefer varchar,
refeq_is_vented varchar,
refeq_license_nbr varchar,
refeq_license_state varchar,
refeq_fed_inspect_exp varchar,
refeq_state_inspect_exp varchar,
refeq_axle_count varchar,
refeq_is_triaxle varchar,
refeq_fits_20 varchar,
refeq_fits_24 varchar,
refeq_fits_30 varchar,
refeq_fits_40 varchar,
refeq_fits_45 varchar,
refeq_fits_48 varchar,
refeq_fits_53 varchar,
refeq_door_kind varchar,
refeq_tows_dolly varchar,
refeq_semi_reefer_kind varchar,
refeq_acry_description varchar,
refeq_tank_rails varchar,
refeq_scope_fk varchar,
refeq_eqtyp_gkey_fk varchar,
refeq_owner_fk varchar,
refeq_operator_fk varchar,
refeq_prior_operator_fk varchar,
refeq_operation varchar,
refeq_timestamp varchar,
refeq_multi_tenant_pk varchar,
refeqty_gkey varchar,
refeqty_id varchar,
refeqty_reference_set varchar,
refeqty_data_source varchar,
refeqty_is_deprecated varchar,
refeqty_is_archetype varchar,
refeqty_archetype varchar,
refeqty_clone_source varchar,
refeqty_basic_length varchar,
refeqty_nominal_length varchar,
refeqty_nominal_height varchar,
refeqty_rfr_type varchar,
refeqty_class varchar,
refeqty_iso_group varchar,
refeqty_length_mm varchar,
refeqty_height_mm varchar,
refeqty_width_mm varchar,
refeqty_tare_weight_kg varchar,
refeqty_safe_weight_kg varchar,
refeqty_description varchar,
refeqty_pict_id varchar,
refeqty_milliteus varchar,
refeqty_uses_accessories varchar,
refeqty_is_temperature_controlled varchar,
refeqty_oog_ok varchar,
refeqty_unsealable varchar,
refeqty_has_wheels varchar,
refeqty_is_open varchar,
refeqty_fits_20 varchar,
refeqty_fits_24 varchar,
refeqty_fits_30 varchar,
refeqty_fits_40 varchar,
refeqty_fits_45 varchar,
refeqty_fits_48 varchar,
refeqty_fits_53 varchar,
refeqty_is_nopick varchar,
refeqty_is_triaxle varchar,
refeqty_is_super_freeze_reefer varchar,
refeqty_is_controlled_atmo_reefer varchar,
refeqty_no_stow_on_if_empty varchar,
refeqty_no_stow_on_if_laden varchar,
refeqty_must_stow_below_deck varchar,
refeqty_must_stow_above_deck varchar,
refeqty_created varchar,
refeqty_creator varchar,
refeqty_changed varchar,
refeqty_changer varchar,
refeqty_life_cycle_state varchar,
refeqty_is_bombcart varchar,
refeqty_is_cassette varchar,
refeqty_teu_capacity varchar,
refeqty_slot_labels varchar,
refeqty_is_2x20NotAllowed varchar,
refeqty_events_type_to_record varchar,
refeqty_reference_set_fk varchar,
refeqty_archetype_fk varchar,
refeqty_clone_source_fk varchar,
refeqty_operation varchar,
refeqty_timestamp varchar,
refeqty_multi_tenant_pk varchar
) WITH (KAFKA_TOPIC='REF_EQUIPMENT_REF_EQUIP_TYPE_STREAM',VALUE_FORMAT='JSON',KEY='refeq_multi_tenant_pk');
